## ---------------------------------------------------------------------------
## get_bia_federally_recognized_tribes.R — BIA federally recognized tribe roster
##
## Returns the authoritative BIA Federal Register list of federally recognized
## tribes and Alaska Native entities — the roster that anchors the Indigenous
## community universe. Sourced by compare_bia_tigris_native_areas.R,
## build_indigenous_tribe_polygons.R, and 02_get_indigenous_universe.R.
## ---------------------------------------------------------------------------
library(tidyverse)

#' Federally recognized Tribal entities (BIA, 2026 Federal Register list)
#'
#' Returns the official list of federally recognized Indian Tribes and Alaska
#' Native entities, exactly as published by the Bureau of Indian Affairs in the
#' Federal Register on 2026-01-30. One row per published list entry.
#'
#' Source: "Indian Entities Recognized by and Eligible To Receive Services From
#'   the United States Bureau of Indian Affairs", 91 FR 4102, FR Doc. 2026-01899.
#'   https://www.federalregister.gov/documents/2026/01/30/2026-01899/indian-entities-recognized-by-and-eligible-to-receive-services-from-the-united-states-bureau-of
#'   Accessed 2026-06-04. This is the first list to include the Lumbee Tribe of
#'   North Carolina (added via the FY2026 NDAA, Pub. L. 119-60).
#'
#' Count reconciliation: the BIA notice states 575 recognized Tribal entities,
#' but prints 577 alphabetized list lines. The difference is 4 cross-reference
#' lines (all in the Alaska section) that merely redirect a former/alternate
#' name to its current canonical entry, e.g. "Arctic Village (See Native Village
#' of Venetie Tribal Government)". Those 4 lines resolve to 2 consolidated
#' canonical entries (Native Village of Venetie Tribal Government; Pribilof
#' Islands Aleut Communities of St. Paul & St. George Islands).
#'
#' Encoding note: the printed lines for those 2 consolidated entries are
#' transcribed below but deliberately commented out (575 active rows = 577
#' printed lines − 2). Their printed names carry long parentheticals while
#' `cross_reference_target` uses the short canonical form, so activating them
#' would split each entity into two distinct names downstream. Consequently
#' `filter(!is_cross_reference)` yields 571 rows and OMITS those 2 entities;
#' to recover the full 573 substantive Tribal entities (348 contiguous +
#' 225 Alaska), fold the redirects into their targets, as
#' `build_indigenous_tribe_polygons()` does:
#' `distinct(if_else(is_cross_reference, cross_reference_target, name))`.
#'
#' Tribal names are reproduced verbatim. Per the BIA's own convention, a former,
#' previously listed, or also-known-as ("aka") name appears in parentheses after
#' the current name; these are kept inline within `name`.
#'
#' @return A tibble with one row per published list entry and columns:
#'   \describe{
#'     \item{name}{Character. Tribal entity name, verbatim as published.}
#'     \item{region}{Character. "Contiguous 48 states" or "Alaska" — the BIA
#'       lists Alaska Native entities in a separate section.}
#'     \item{alaska_native}{Logical. `TRUE` for Alaska Native entities
#'       (equivalent to `region == "Alaska"`).}
#'     \item{is_cross_reference}{Logical. `TRUE` for the 4 alphabetical
#'       "(See ...)" redirect lines that are not counted as distinct entities.}
#'     \item{cross_reference_target}{Character. For cross-reference rows, the
#'       canonical entry the line redirects to; `NA` otherwise.}
#'   }
#' 
get_bia_federally_recognized_tribes <- function() {
  tribble(
    ~name, ~region, ~alaska_native, ~is_cross_reference, ~cross_reference_target,
    "Absentee-Shawnee Tribe of Indians of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Agua Caliente Band of Cahuilla Indians of the Agua Caliente Indian Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ak-Chin Indian Community", "Contiguous 48 states", FALSE, FALSE, NA,
    "Alabama-Coushatta Tribe of Texas", "Contiguous 48 states", FALSE, FALSE, NA,
    "Alabama-Quassarte Tribal Town", "Contiguous 48 states", FALSE, FALSE, NA,
    "Alturas Indian Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Apache Tribe of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Assiniboine and Sioux Tribes of the Fort Peck Indian Reservation, Montana", "Contiguous 48 states", FALSE, FALSE, NA,
    "Augustine Band of Cahuilla Indians, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Bad River Band of the Lake Superior Tribe of Chippewa Indians of the Bad River Reservation, Wisconsin", "Contiguous 48 states", FALSE, FALSE, NA,
    "Bay Mills Indian Community, Michigan", "Contiguous 48 states", FALSE, FALSE, NA,
    "Bear River Band of the Rohnerville Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Berry Creek Rancheria of Maidu Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Big Lagoon Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Big Pine Paiute Tribe of the Owens Valley", "Contiguous 48 states", FALSE, FALSE, NA,
    "Big Sandy Rancheria of Western Mono Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Big Valley Band of Pomo Indians of the Big Valley Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Bishop Paiute Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Blackfeet Tribe of the Blackfeet Indian Reservation of Montana", "Contiguous 48 states", FALSE, FALSE, NA,
    "Blue Lake Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Bridgeport Indian Colony", "Contiguous 48 states", FALSE, FALSE, NA,
    "Buena Vista Rancheria of Me-Wuk Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Burns Paiute Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cabazon Band of Cahuilla Indians (previously listed as Cabazon Band of Mission Indians, California)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cachil DeHe Band of Wintun Indians of the Colusa Indian Community of the Colusa Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Caddo Nation of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cahto Tribe of the Laytonville Rancheria", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cahuilla Band of Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "California Valley Miwok Tribe, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Campo Band of Diegueno Mission Indians of the Campo Indian Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Capitan Grande Band of Diegueno Mission Indians of California (Barona Group of Capitan Grande Band of Mission Indians of the Barona Reservation, California; Viejas (Baron Long) Group of Capitan Grande Band of Mission Indians of the Viejas Reservation, California)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Catawba Indian Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cayuga Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cedarville Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Chemehuevi Indian Tribe of the Chemehuevi Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cher-Ae Heights Indian Community of the Trinidad Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cherokee Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cheyenne and Arapaho Tribes, Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cheyenne River Sioux Tribe of the Cheyenne River Reservation, South Dakota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Chickahominy Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Chickahominy Indian Tribe—Eastern Division", "Contiguous 48 states", FALSE, FALSE, NA,
    "Chicken Ranch Rancheria of Me-Wuk Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Chippewa Cree Indians of the Rocky Boy's Reservation, Montana", "Contiguous 48 states", FALSE, FALSE, NA,
    "Chitimacha Tribe of Louisiana", "Contiguous 48 states", FALSE, FALSE, NA,
    "Citizen Potawatomi Nation, Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cloverdale Rancheria of Pomo Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cocopah Tribe of Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Coeur D'Alene Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cold Springs Rancheria of Mono Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Colorado River Indian Tribes of the Colorado River Indian Reservation, Arizona and California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Comanche Nation, Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Confederated Salish and Kootenai Tribes of the Flathead Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Confederated Tribes and Bands of the Yakama Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Confederated Tribes of Siletz Indians of Oregon", "Contiguous 48 states", FALSE, FALSE, NA,
    "Confederated Tribes of the Chehalis Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Confederated Tribes of the Colville Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Confederated Tribes of the Coos, Lower Umpqua and Siuslaw Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Confederated Tribes of the Goshute Reservation, Nevada and Utah", "Contiguous 48 states", FALSE, FALSE, NA,
    "Confederated Tribes of the Grand Ronde Community of Oregon", "Contiguous 48 states", FALSE, FALSE, NA,
    "Confederated Tribes of the Umatilla Indian Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Confederated Tribes of the Warm Springs Reservation of Oregon", "Contiguous 48 states", FALSE, FALSE, NA,
    "Coquille Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Coushatta Tribe of Louisiana", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cow Creek Band of Umpqua Tribe of Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Cowlitz Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Coyote Valley Band of Pomo Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Crow Creek Sioux Tribe of the Crow Creek Reservation, South Dakota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Crow Tribe of Montana", "Contiguous 48 states", FALSE, FALSE, NA,
    "Delaware Nation, Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Delaware Tribe of Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Dry Creek Rancheria Band of Pomo Indians, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Duckwater Shoshone Tribe (previously listed as Duckwater Shoshone Tribe of the Duckwater Reservation, Nevada)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Eastern Band of Cherokee Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Eastern Shawnee Tribe of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Eastern Shoshone Tribe of the Wind River Reservation, Wyoming", "Contiguous 48 states", FALSE, FALSE, NA,
    "Elem Indian Colony of Pomo Indians of the Sulphur Bank Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Elk Valley Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ely Shoshone Tribe of Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Enterprise Rancheria of Maidu Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ewiiaapaayp Band of Kumeyaay Indians (previously listed as Ewiiaapaayp Band of Kumeyaay Indians, California)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Federated Indians of Graton Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Flandreau Santee Sioux Tribe of South Dakota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Forest County Potawatomi Community, Wisconsin", "Contiguous 48 states", FALSE, FALSE, NA,
    "Fort Belknap Indian Community of the Fort Belknap Reservation of Montana", "Contiguous 48 states", FALSE, FALSE, NA,
    "Fort Bidwell Indian Community of the Fort Bidwell Reservation of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Fort Independence Indian Community of Paiute Indians of the Fort Independence Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Fort McDermitt Paiute and Shoshone Tribes of the Fort McDermitt Indian Reservation, Nevada and Oregon", "Contiguous 48 states", FALSE, FALSE, NA,
    "Fort McDowell Yavapai Nation, Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Fort Mojave Indian Tribe of Arizona, California & Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Fort Sill—Chiricahua—Warm Springs—Apache Tribe (previously listed as Fort Sill Apache Tribe of Oklahoma)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Gila River Indian Community of the Gila River Indian Reservation, Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Grand Traverse Band of Ottawa and Chippewa Indians, Michigan", "Contiguous 48 states", FALSE, FALSE, NA,
    "Greenville Rancheria", "Contiguous 48 states", FALSE, FALSE, NA,
    "Grindstone Indian Rancheria of Wintun-Wailaki Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Guidiville Rancheria of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Habematolel Pomo of Upper Lake, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Hannahville Indian Community, Michigan", "Contiguous 48 states", FALSE, FALSE, NA,
    "Havasupai Tribe of the Havasupai Reservation, Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ho-Chunk Nation of Wisconsin", "Contiguous 48 states", FALSE, FALSE, NA,
    "Hoh Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Hoopa Valley Tribe, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Hopi Tribe of Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Hopland Band of Pomo Indians, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Houlton Band of Maliseet Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Hualapai Indian Tribe of the Hualapai Indian Reservation, Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Iipay Nation of Santa Ysabel, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Inaja Band of Diegueno Mission Indians of the Inaja and Cosmit Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ione Band of Miwok Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Iowa Tribe of Kansas and Nebraska", "Contiguous 48 states", FALSE, FALSE, NA,
    "Iowa Tribe of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Jackson Band of Miwuk Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Jamestown S'Klallam Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Jamul Indian Village of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Jena Band of Choctaw Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Jicarilla Apache Nation, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Kaibab Band of Paiute Indians of the Kaibab Indian Reservation, Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Kalispel Indian Community of the Kalispel Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Karuk Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Kashia Band of Pomo Indians of the Stewarts Point Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Kaw Nation, Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Keweenaw Bay Indian Community, Michigan", "Contiguous 48 states", FALSE, FALSE, NA,
    "Kialegee Tribal Town", "Contiguous 48 states", FALSE, FALSE, NA,
    "Kickapoo Traditional Tribe of Texas", "Contiguous 48 states", FALSE, FALSE, NA,
    "Kickapoo Tribe of Indians of the Kickapoo Reservation in Kansas", "Contiguous 48 states", FALSE, FALSE, NA,
    "Kickapoo Tribe of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Kiowa Tribe (previously listed as Kiowa Indian Tribe of Oklahoma)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Klamath Tribes", "Contiguous 48 states", FALSE, FALSE, NA,
    "Kletsel Dehe Wintun Nation of the Cortina Rancheria (previously listed as Kletsel Dehe Band of Wintun Indians)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Koi Nation of Northern California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Kootenai Tribe of Idaho", "Contiguous 48 states", FALSE, FALSE, NA,
    "La Jolla Band of Luiseno Indians, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "La Posta Band of Diegueno Mission Indians of the La Posta Indian Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Lac Courte Oreilles Band of Lake Superior Chippewa Indians of Wisconsin", "Contiguous 48 states", FALSE, FALSE, NA,
    "Lac du Flambeau Band of Lake Superior Chippewa Indians of the Lac du Flambeau Reservation of Wisconsin", "Contiguous 48 states", FALSE, FALSE, NA,
    "Lac Vieux Desert Band of Lake Superior Chippewa Indians of Michigan", "Contiguous 48 states", FALSE, FALSE, NA,
    "Las Vegas Tribe of Paiute Indians of the Las Vegas Indian Colony, Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Little River Band of Ottawa Indians, Michigan", "Contiguous 48 states", FALSE, FALSE, NA,
    "Little Shell Tribe of Chippewa Indians of Montana", "Contiguous 48 states", FALSE, FALSE, NA,
    "Little Traverse Bay Bands of Odawa Indians, Michigan", "Contiguous 48 states", FALSE, FALSE, NA,
    "Lone Pine Paiute-Shoshone Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Los Coyotes Band of Cahuilla and Cupeno Indians, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Lovelock Paiute Tribe of the Lovelock Indian Colony, Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Lower Brule Sioux Tribe of the Lower Brule Reservation, South Dakota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Lower Elwha Tribal Community", "Contiguous 48 states", FALSE, FALSE, NA,
    "Lower Sioux Indian Community in the State of Minnesota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Lumbee Tribe of North Carolina (See Supplementary Information supra, noting conditions on the Tribe's eligibility for Federal services)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Lummi Tribe of the Lummi Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Lytton Rancheria of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Makah Indian Tribe of the Makah Indian Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Manchester Band of Pomo Indians of the Manchester Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Manzanita Band of Diegueno Mission Indians of the Manzanita Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Mashantucket Pequot Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Mashpee Wampanoag Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Match-E-Be-Nash-She-Wish Band of Pottawatomi (previously listed as Match-E-Be-Nash-She-Wish Band of Pottawatomi Indians of Michigan)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Mechoopda Indian Tribe of Chico Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Menominee Indian Tribe of Wisconsin", "Contiguous 48 states", FALSE, FALSE, NA,
    "Mesa Grande Band of Diegueno Mission Indians of the Mesa Grande Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Mescalero Apache Tribe of the Mescalero Reservation, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Miami Tribe of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Miccosukee Tribe of Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Middletown Rancheria of Pomo Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Mi'kmaq Nation (previously listed as Aroostook Band of Micmacs)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Minnesota Chippewa Tribe, Minnesota (Six component reservations: Bois Forte Band (Nett Lake); Fond du Lac Band; Grand Portage Band; Leech Lake Band; Mille Lacs Band; White Earth Band)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Mississippi Band of Choctaw Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Moapa Band of Paiute Indians of the Moapa River Indian Reservation, Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Modoc Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Mohegan Tribe of Indians of Connecticut", "Contiguous 48 states", FALSE, FALSE, NA,
    "Monacan Indian Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Mooretown Rancheria of Maidu Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Morongo Band of Mission Indians, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Muckleshoot Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Nansemond Indian Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Narragansett Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Navajo Nation, Arizona, New Mexico, & Utah", "Contiguous 48 states", FALSE, FALSE, NA,
    "Nez Perce Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Nisqually Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Nooksack Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Northern Arapaho Tribe of the Wind River Reservation, Wyoming", "Contiguous 48 states", FALSE, FALSE, NA,
    "Northern Cheyenne Tribe of the Northern Cheyenne Indian Reservation, Montana", "Contiguous 48 states", FALSE, FALSE, NA,
    "Northfork Rancheria of Mono Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Northwestern Band of the Shoshone Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Nottawaseppi Huron Band of the Potawatomi, Michigan", "Contiguous 48 states", FALSE, FALSE, NA,
    "Oglala Sioux Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ohkay Owingeh, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Omaha Tribe of Nebraska", "Contiguous 48 states", FALSE, FALSE, NA,
    "Oneida Indian Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Oneida Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Onondaga Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Otoe-Missouria Tribe of Indians, Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ottawa Tribe of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Paiute Indian Tribe of Utah (Cedar Band of Paiutes, Kanosh Band of Paiutes, Koosharem Band of Paiutes, Indian Peaks Band of Paiutes, and Shivwits Band of Paiutes)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Paiute-Shoshone Tribe of the Fallon Reservation and Colony, Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pala Band of Mission Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pamunkey Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pascua Yaqui Tribe of Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Paskenta Band of Nomlaki Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Passamaquoddy Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pauma Band of Luiseno Mission Indians of the Pauma & Yuima Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pawnee Nation of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pechanga Band of Indians (previously listed as Pechanga Band of Luiseno Mission Indians of the Pechanga Reservation, California)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Penobscot Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Peoria Tribe of Indians of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Picayune Rancheria of Chukchansi Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pinoleville Pomo Nation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pit River Tribe, California (includes XL Ranch, Big Bend, Likely, Lookout, Montgomery Creek, and Roaring Creek Rancherias)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Poarch Band of Creek Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pokagon Band of Potawatomi Indians, Michigan and Indiana", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ponca Tribe of Indians of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ponca Tribe of Nebraska", "Contiguous 48 states", FALSE, FALSE, NA,
    "Port Gamble S'Klallam Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Potter Valley Tribe, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Prairie Band Potawatomi Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Prairie Island Indian Community in the State of Minnesota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Acoma, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Cochiti, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Isleta, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Jemez, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Laguna, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Nambe, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Picuris, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Pojoaque, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of San Felipe, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of San Ildefonso, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Sandia, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Santa Ana, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Santa Clara, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Taos, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Tesuque, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pueblo of Zia, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "PuliklaTribe of Yurok People (previously listed as Resighini Rancheria, California)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Puyallup Tribe of the Puyallup Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Pyramid Lake Paiute Tribe of the Pyramid Lake Reservation, Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Quapaw Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Quartz Valley Indian Community of the Quartz Valley Reservation of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Quechan Tribe of the Fort Yuma Indian Reservation, California & Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Quileute Tribe of the Quileute Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Quinault Indian Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ramona Band of Cahuilla, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Rappahannock Tribe, Inc.", "Contiguous 48 states", FALSE, FALSE, NA,
    "Red Cliff Band of Lake Superior Chippewa Indians of Wisconsin", "Contiguous 48 states", FALSE, FALSE, NA,
    "Red Lake Band of Chippewa Indians, Minnesota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Redding Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Redwood Valley or Little River Band of Pomo Indians of the Redwood Valley Rancheria California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Reno-Sparks Indian Colony, Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Rincon Band of Luiseno Indians (previously listed as Rincon Band of Luiseno Mission Indians of Rincon Reservation, California)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Robinson Rancheria", "Contiguous 48 states", FALSE, FALSE, NA,
    "Rosebud Sioux Tribe of the Rosebud Indian Reservation, South Dakota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Round Valley Indian Tribes, Round Valley Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Sac & Fox Nation of Missouri in Kansas and Nebraska", "Contiguous 48 states", FALSE, FALSE, NA,
    "Sac & Fox Nation, Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Sac & Fox Tribe of the Mississippi in Iowa", "Contiguous 48 states", FALSE, FALSE, NA,
    "Saginaw Chippewa Indian Tribe of Michigan", "Contiguous 48 states", FALSE, FALSE, NA,
    "Saint Regis Mohawk Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Salt River Pima-Maricopa Indian Community of the Salt River Reservation, Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Samish Indian Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "San Carlos Apache Tribe of the San Carlos Reservation, Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "San Juan Southern Paiute Tribe of Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "San Pasqual Band of Diegueno Mission Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Santa Rosa Band of Cahuilla Indians, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Santa Rosa Indian Community of the Santa Rosa Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Santa Ynez Band of Chumash Mission Indians of the Santa Ynez Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Santee Sioux Nation, Nebraska", "Contiguous 48 states", FALSE, FALSE, NA,
    "Santo Domingo Pueblo", "Contiguous 48 states", FALSE, FALSE, NA,
    "Sauk-Suiattle Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Sault Ste. Marie Tribe of Chippewa Indians, Michigan", "Contiguous 48 states", FALSE, FALSE, NA,
    "Scotts Valley Band of Pomo Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Seminole Tribe of Florida", "Contiguous 48 states", FALSE, FALSE, NA,
    "Seneca Nation of Indians", "Contiguous 48 states", FALSE, FALSE, NA,
    "Seneca-Cayuga Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Shakopee Mdewakanton Sioux Community of Minnesota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Shawnee Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Sherwood Valley Rancheria of Pomo Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Shingle Springs Band of Miwok Indians, Shingle Springs Rancheria (Verona Tract), California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Shinnecock Indian Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Shoalwater Bay Indian Tribe of the Shoalwater Bay Indian Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Shoshone-Bannock Tribes of the Fort Hall Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Shoshone-Paiute Tribes of the Duck Valley Reservation, Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Sisseton-Wahpeton Oyate of the Lake Traverse Reservation, South Dakota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Skokomish Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Skull Valley Band of Goshute Indians of Utah", "Contiguous 48 states", FALSE, FALSE, NA,
    "Snoqualmie Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Soboba Band of Luiseno Indians, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Sokaogon Chippewa Community, Wisconsin", "Contiguous 48 states", FALSE, FALSE, NA,
    "Southern Ute Indian Tribe of the Southern Ute Reservation, Colorado", "Contiguous 48 states", FALSE, FALSE, NA,
    "Spirit Lake Tribe, North Dakota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Spokane Tribe of the Spokane Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Squaxin Island Tribe of the Squaxin Island Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "St. Croix Chippewa Indians of Wisconsin", "Contiguous 48 states", FALSE, FALSE, NA,
    "Standing Rock Sioux Tribe of North & South Dakota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Stillaguamish Tribe of Indians of Washington", "Contiguous 48 states", FALSE, FALSE, NA,
    "Stockbridge Munsee Community, Wisconsin", "Contiguous 48 states", FALSE, FALSE, NA,
    "Summit Lake Paiute Tribe of Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Suquamish Indian Tribe of the Port Madison Reservation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Susanville Indian Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Swinomish Indian Tribal Community", "Contiguous 48 states", FALSE, FALSE, NA,
    "Sycuan Band of the Kumeyaay Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Table Mountain Rancheria", "Contiguous 48 states", FALSE, FALSE, NA,
    "Tejon Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Te-Moak Tribe of Western Shoshone Indians of Nevada (Four constituent bands: Battle Mountain Band; Elko Band; South Fork Band; and Wells Band)", "Contiguous 48 states", FALSE, FALSE, NA,
    "The Chickasaw Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "The Choctaw Nation of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "The Muscogee (Creek) Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "The Osage Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "The Seminole Nation of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Thlopthlocco Tribal Town", "Contiguous 48 states", FALSE, FALSE, NA,
    "Three Affiliated Tribes of the Fort Berthold Reservation, North Dakota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Timbisha Shoshone Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Tohono O'odham Nation of Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Tolowa Dee-ni' Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Tonawanda Band of Seneca", "Contiguous 48 states", FALSE, FALSE, NA,
    "Tonkawa Tribe of Indians of Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Tonto Apache Tribe of Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Torres Martinez Desert Cahuilla Indians, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Tulalip Tribes of Washington", "Contiguous 48 states", FALSE, FALSE, NA,
    "Tule River Indian Tribe of the Tule River Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Tunica-Biloxi Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Tuolumne Band of Me-Wuk Indians of the Tuolumne Rancheria of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Turtle Mountain Band of Chippewa Indians of North Dakota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Tuscarora Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Twenty-Nine Palms Band of Mission Indians of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "United Auburn Indian Community of the Auburn Rancheria of California", "Contiguous 48 states", FALSE, FALSE, NA,
    "United Keetoowah Band of Cherokee Indians in Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Upper Mattaponi Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Upper Sioux Community, Minnesota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Upper Skagit Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ute Indian Tribe of the Uintah & Ouray Reservation, Utah", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ute Mountain Ute Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Utu Utu Gwaitu Paiute Tribe of the Benton Paiute Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Walker River Paiute Tribe of the Walker River Reservation, Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Wampanoag Tribe of Gay Head (Aquinnah)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Washoe Tribe of Nevada & California (Carson Colony, Dresslerville Colony, Woodfords Community, Stewart Community, & Washoe Ranches)", "Contiguous 48 states", FALSE, FALSE, NA,
    "White Mountain Apache Tribe of the Fort Apache Reservation, Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Wichita and Affiliated Tribes (Wichita, Keechi, Waco, & Tawakonie), Oklahoma", "Contiguous 48 states", FALSE, FALSE, NA,
    "Wilton Rancheria, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Winnebago Tribe of Nebraska", "Contiguous 48 states", FALSE, FALSE, NA,
    "Winnemucca Indian Colony of Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Wiyot Tribe, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Wyandotte Nation", "Contiguous 48 states", FALSE, FALSE, NA,
    "Yankton Sioux Tribe of South Dakota", "Contiguous 48 states", FALSE, FALSE, NA,
    "Yavapai-Apache Nation of the Camp Verde Indian Reservation, Arizona", "Contiguous 48 states", FALSE, FALSE, NA,
    "Yavapai-Prescott Indian Tribe", "Contiguous 48 states", FALSE, FALSE, NA,
    "Yerington Paiute Tribe of the Yerington Colony & Campbell Ranch, Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Yocha Dehe Wintun Nation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Yomba Shoshone Tribe of the Yomba Reservation, Nevada", "Contiguous 48 states", FALSE, FALSE, NA,
    "Ysleta del Sur Pueblo", "Contiguous 48 states", FALSE, FALSE, NA,
    "Yuhaaviatam of San Manuel Nation (previously listed as San Manuel Band of Mission Indians, California)", "Contiguous 48 states", FALSE, FALSE, NA,
    "Yurok Tribe of the Yurok Reservation, California", "Contiguous 48 states", FALSE, FALSE, NA,
    "Zuni Tribe of the Zuni Reservation, New Mexico", "Contiguous 48 states", FALSE, FALSE, NA,
    "Agdaagux Tribe of King Cove", "Alaska", TRUE, FALSE, NA,
    "Akiachak Native Community", "Alaska", TRUE, FALSE, NA,
    "Akiak Native Community", "Alaska", TRUE, FALSE, NA,
    "Alatna Village", "Alaska", TRUE, FALSE, NA,
    "Algaaciq Native Village (St. Mary's)", "Alaska", TRUE, FALSE, NA,
    "Allakaket Village", "Alaska", TRUE, FALSE, NA,
    "Aleut Community of St. Paul Island (See Pribilof Islands Aleut Communities of St. Paul & St. George Islands) (previously listed as Saint Paul Island ( See Pribilof Islands Aleut Communities of St. Paul & St. George Islands))", "Alaska", TRUE, TRUE, "Pribilof Islands Aleut Communities of St. Paul & St. George Islands",
    "Alutiiq Tribe of Old Harbor", "Alaska", TRUE, FALSE, NA,
    "Angoon Community Association", "Alaska", TRUE, FALSE, NA,
    "Anvik Village", "Alaska", TRUE, FALSE, NA,
    "Arctic Village (See Native Village of Venetie Tribal Government)", "Alaska", TRUE, TRUE, "Native Village of Venetie Tribal Government",
    "Asa'carsarmiut Tribe", "Alaska", TRUE, FALSE, NA,
    "Beaver Village", "Alaska", TRUE, FALSE, NA,
    "Birch Creek Tribe", "Alaska", TRUE, FALSE, NA,
    "Central Council of the Tlingit & Haida Indian Tribes", "Alaska", TRUE, FALSE, NA,
    "Chalkyitsik Village", "Alaska", TRUE, FALSE, NA,
    "Cheesh-Na Tribe", "Alaska", TRUE, FALSE, NA,
    "Chevak Native Village", "Alaska", TRUE, FALSE, NA,
    "Chickaloon Native Village", "Alaska", TRUE, FALSE, NA,
    "Chignik Bay Tribal Council", "Alaska", TRUE, FALSE, NA,
    "Chignik Lake Village", "Alaska", TRUE, FALSE, NA,
    "Chilkat Indian Village (Klukwan)", "Alaska", TRUE, FALSE, NA,
    "Chilkoot Indian Association (Haines)", "Alaska", TRUE, FALSE, NA,
    "Chinik Eskimo Community (Golovin)", "Alaska", TRUE, FALSE, NA,
    "Chuloonawick Native Village", "Alaska", TRUE, FALSE, NA,
    "Circle Native Community", "Alaska", TRUE, FALSE, NA,
    "Craig Tribal Association", "Alaska", TRUE, FALSE, NA,
    "Curyung Tribal Council", "Alaska", TRUE, FALSE, NA,
    "Douglas Indian Association", "Alaska", TRUE, FALSE, NA,
    "Egegik Village", "Alaska", TRUE, FALSE, NA,
    "Eklutna Native Village", "Alaska", TRUE, FALSE, NA,
    "Emmonak Village", "Alaska", TRUE, FALSE, NA,
    "Evansville Village (aka Bettles Field)", "Alaska", TRUE, FALSE, NA,
    "Gulkana Village Council", "Alaska", TRUE, FALSE, NA,
    "Healy Lake Village", "Alaska", TRUE, FALSE, NA,
    "Holy Cross Tribe", "Alaska", TRUE, FALSE, NA,
    "Hoonah Indian Association", "Alaska", TRUE, FALSE, NA,
    "Hughes Village", "Alaska", TRUE, FALSE, NA,
    "Huslia Village", "Alaska", TRUE, FALSE, NA,
    "Hydaburg Cooperative Association", "Alaska", TRUE, FALSE, NA,
    "Igiugig Village", "Alaska", TRUE, FALSE, NA,
    "Inupiat Community of the Arctic Slope", "Alaska", TRUE, FALSE, NA,
    "Iqugmiut Traditional Council", "Alaska", TRUE, FALSE, NA,
    "Ivanof Bay Tribe", "Alaska", TRUE, FALSE, NA,
    "Kaguyak Village", "Alaska", TRUE, FALSE, NA,
    "Kaktovik Village (aka Barter Island)", "Alaska", TRUE, FALSE, NA,
    "Kasigluk Traditional Elders Council", "Alaska", TRUE, FALSE, NA,
    "Kenaitze Indian Tribe", "Alaska", TRUE, FALSE, NA,
    "Ketchikan Indian Community", "Alaska", TRUE, FALSE, NA,
    "King Island Native Community", "Alaska", TRUE, FALSE, NA,
    "King Salmon Tribe", "Alaska", TRUE, FALSE, NA,
    "Klawock Cooperative Association", "Alaska", TRUE, FALSE, NA,
    "Knik Tribe", "Alaska", TRUE, FALSE, NA,
    "Kokhanok Village", "Alaska", TRUE, FALSE, NA,
    "Koyukuk Native Village", "Alaska", TRUE, FALSE, NA,
    "Levelock Village", "Alaska", TRUE, FALSE, NA,
    "Lime Village", "Alaska", TRUE, FALSE, NA,
    "Louden Tribe (previously listed as Galena Village (aka Louden Village))", "Alaska", TRUE, FALSE, NA,
    "Manley Hot Springs Village", "Alaska", TRUE, FALSE, NA,
    "Manokotak Village", "Alaska", TRUE, FALSE, NA,
    "McGrath Native Village", "Alaska", TRUE, FALSE, NA,
    "Mentasta Traditional Council", "Alaska", TRUE, FALSE, NA,
    "Metlakatla Indian Community, Annette Island Reserve", "Alaska", TRUE, FALSE, NA,
    "Naknek Native Village", "Alaska", TRUE, FALSE, NA,
    "Native Village of Afognak", "Alaska", TRUE, FALSE, NA,
    "Native Village of Akhiok", "Alaska", TRUE, FALSE, NA,
    "Native Village of Akutan", "Alaska", TRUE, FALSE, NA,
    "Native Village of Aleknagik", "Alaska", TRUE, FALSE, NA,
    "Native Village of Ambler", "Alaska", TRUE, FALSE, NA,
    "Native Village of Atka", "Alaska", TRUE, FALSE, NA,
    "Native Village of Atqasuk", "Alaska", TRUE, FALSE, NA,
    "Native Village of Barrow Inupiat Traditional Government", "Alaska", TRUE, FALSE, NA,
    "Native Village of Belkofski", "Alaska", TRUE, FALSE, NA,
    "Native Village of Brevig Mission", "Alaska", TRUE, FALSE, NA,
    "Native Village of Buckland", "Alaska", TRUE, FALSE, NA,
    "Native Village of Cantwell", "Alaska", TRUE, FALSE, NA,
    "Native Village of Chenega", "Alaska", TRUE, FALSE, NA,
    "Native Village of Chignik Lagoon", "Alaska", TRUE, FALSE, NA,
    "Native Village of Chitina", "Alaska", TRUE, FALSE, NA,
    "Native Village of Chuathbaluk (Russian Mission, Kuskokwim)", "Alaska", TRUE, FALSE, NA,
    "Native Village of Council", "Alaska", TRUE, FALSE, NA,
    "Native Village of Deering", "Alaska", TRUE, FALSE, NA,
    "Native Village of Diomede (aka Inalik)", "Alaska", TRUE, FALSE, NA,
    "Native Village of Eagle", "Alaska", TRUE, FALSE, NA,
    "Native Village of Eek", "Alaska", TRUE, FALSE, NA,
    "Native Village of Ekuk", "Alaska", TRUE, FALSE, NA,
    "Native Village of Ekwok", "Alaska", TRUE, FALSE, NA,
    "Native Village of Elim", "Alaska", TRUE, FALSE, NA,
    "Native Village of Eyak (Cordova)", "Alaska", TRUE, FALSE, NA,
    "Native Village of False Pass", "Alaska", TRUE, FALSE, NA,
    "Native Village of Fort Yukon", "Alaska", TRUE, FALSE, NA,
    "Native Village of Gakona", "Alaska", TRUE, FALSE, NA,
    "Native Village of Gambell", "Alaska", TRUE, FALSE, NA,
    "Native Village of Georgetown", "Alaska", TRUE, FALSE, NA,
    "Native Village of Goodnews Bay", "Alaska", TRUE, FALSE, NA,
    "Native Village of Hamilton", "Alaska", TRUE, FALSE, NA,
    "Native Village of Hooper Bay", "Alaska", TRUE, FALSE, NA,
    "Native Village of Kanatak", "Alaska", TRUE, FALSE, NA,
    "Native Village of Karluk", "Alaska", TRUE, FALSE, NA,
    "Native Village of Kiana", "Alaska", TRUE, FALSE, NA,
    "Native Village of Kipnuk", "Alaska", TRUE, FALSE, NA,
    "Native Village of Kivalina", "Alaska", TRUE, FALSE, NA,
    "Native Village of Kluti Kaah (aka Copper Center)", "Alaska", TRUE, FALSE, NA,
    "Native Village of Kobuk", "Alaska", TRUE, FALSE, NA,
    "Native Village of Kongiganak", "Alaska", TRUE, FALSE, NA,
    "Native Village of Kotzebue", "Alaska", TRUE, FALSE, NA,
    "Native Village of Koyuk", "Alaska", TRUE, FALSE, NA,
    "Native Village of Kwigillingok", "Alaska", TRUE, FALSE, NA,
    "Native Village of Kwinhagak (aka Quinhagak)", "Alaska", TRUE, FALSE, NA,
    "Native Village of Larsen Bay", "Alaska", TRUE, FALSE, NA,
    "Native Village of Marshall (aka Fortuna Ledge)", "Alaska", TRUE, FALSE, NA,
    "Native Village of Mary's Igloo", "Alaska", TRUE, FALSE, NA,
    "Native Village of Mekoryuk", "Alaska", TRUE, FALSE, NA,
    "Native Village of Minto", "Alaska", TRUE, FALSE, NA,
    "Native Village of Nanwalek (aka English Bay)", "Alaska", TRUE, FALSE, NA,
    "Native Village of Napaimute", "Alaska", TRUE, FALSE, NA,
    "Native Village of Napakiak", "Alaska", TRUE, FALSE, NA,
    "Native Village of Napaskiak", "Alaska", TRUE, FALSE, NA,
    "Native Village of Nelson Lagoon", "Alaska", TRUE, FALSE, NA,
    "Native Village of Nightmute", "Alaska", TRUE, FALSE, NA,
    "Native Village of Nikolski", "Alaska", TRUE, FALSE, NA,
    "Native Village of Noatak", "Alaska", TRUE, FALSE, NA,
    "Native Village of Nuiqsut (aka Nooiksut)", "Alaska", TRUE, FALSE, NA,
    "Native Village of Nunam Iqua", "Alaska", TRUE, FALSE, NA,
    "Native Village of Nunapitchuk", "Alaska", TRUE, FALSE, NA,
    "Native Village of Ouzinkie", "Alaska", TRUE, FALSE, NA,
    "Native Village of Paimiut", "Alaska", TRUE, FALSE, NA,
    "Native Village of Perryville", "Alaska", TRUE, FALSE, NA,
    "Native Village of Pilot Point", "Alaska", TRUE, FALSE, NA,
    "Native Village of Point Hope", "Alaska", TRUE, FALSE, NA,
    "Native Village of Point Lay", "Alaska", TRUE, FALSE, NA,
    "Native Village of Port Graham", "Alaska", TRUE, FALSE, NA,
    "Native Village of Port Heiden", "Alaska", TRUE, FALSE, NA,
    "Native Village of Port Lions", "Alaska", TRUE, FALSE, NA,
    "Native Village of Ruby", "Alaska", TRUE, FALSE, NA,
    "Native Village of Saint Michael", "Alaska", TRUE, FALSE, NA,
    "Native Village of Savoonga", "Alaska", TRUE, FALSE, NA,
    "Native Village of Scammon Bay", "Alaska", TRUE, FALSE, NA,
    "Native Village of Selawik", "Alaska", TRUE, FALSE, NA,
    "Native Village of Shaktoolik", "Alaska", TRUE, FALSE, NA,
    "Native Village of Shishmaref", "Alaska", TRUE, FALSE, NA,
    "Native Village of Shungnak", "Alaska", TRUE, FALSE, NA,
    "Native Village of South Naknek (previously listed as South Naknek Village)", "Alaska", TRUE, FALSE, NA,
    "Native Village of Stevens", "Alaska", TRUE, FALSE, NA,
    "Native Village of Tanacross", "Alaska", TRUE, FALSE, NA,
    "Native Village of Tanana", "Alaska", TRUE, FALSE, NA,
    "Native Village of Tatitlek", "Alaska", TRUE, FALSE, NA,
    "Native Village of Tazlina", "Alaska", TRUE, FALSE, NA,
    "Native Village of Teller", "Alaska", TRUE, FALSE, NA,
    "Native Village of Tetlin", "Alaska", TRUE, FALSE, NA,
    "Native Village of Tuntutuliak", "Alaska", TRUE, FALSE, NA,
    "Native Village of Tununak", "Alaska", TRUE, FALSE, NA,
    "Native Village of Tyonek", "Alaska", TRUE, FALSE, NA,
    "Native Village of Unalakleet", "Alaska", TRUE, FALSE, NA,
    "Native Village of Unga", "Alaska", TRUE, FALSE, NA,
    ## Printed line for the consolidated Venetie entity — intentionally inactive:
    ## the entity is recovered via its two "(See ...)" redirects' short-form
    ## cross_reference_target; activating this long parenthetical form would
    ## split the entity into two distinct names downstream.
    #"Native Village of Venetie Tribal Government (Arctic Village and Village of Venetie)", "Alaska", TRUE, FALSE, NA,
    "Native Village of Wales", "Alaska", TRUE, FALSE, NA,
    "Native Village of White Mountain", "Alaska", TRUE, FALSE, NA,
    "Nenana Native Association", "Alaska", TRUE, FALSE, NA,
    "New Koliganek Village Council", "Alaska", TRUE, FALSE, NA,
    "New Stuyahok Village", "Alaska", TRUE, FALSE, NA,
    "Newhalen Village", "Alaska", TRUE, FALSE, NA,
    "Newtok Village", "Alaska", TRUE, FALSE, NA,
    "Nikolai Village", "Alaska", TRUE, FALSE, NA,
    "Ninilchik Village", "Alaska", TRUE, FALSE, NA,
    "Nome Eskimo Community", "Alaska", TRUE, FALSE, NA,
    "Nondalton Tribe (previously listed as Nondalton Village)", "Alaska", TRUE, FALSE, NA,
    "Noorvik Native Community", "Alaska", TRUE, FALSE, NA,
    "Northway Village", "Alaska", TRUE, FALSE, NA,
    "Nulato Village", "Alaska", TRUE, FALSE, NA,
    "Nunakauyarmiut Tribe", "Alaska", TRUE, FALSE, NA,
    "Organized Village of Grayling (aka Holikachuk)", "Alaska", TRUE, FALSE, NA,
    "Organized Village of Kake", "Alaska", TRUE, FALSE, NA,
    "Organized Village of Kasaan", "Alaska", TRUE, FALSE, NA,
    "Organized Village of Kwethluk", "Alaska", TRUE, FALSE, NA,
    "Organized Village of Saxman", "Alaska", TRUE, FALSE, NA,
    "Orutsararmiut Traditional Native Council", "Alaska", TRUE, FALSE, NA,
    "Oscarville Traditional Village", "Alaska", TRUE, FALSE, NA,
    "Pauloff Harbor Village", "Alaska", TRUE, FALSE, NA,
    "Pedro Bay Village", "Alaska", TRUE, FALSE, NA,
    "Petersburg Indian Association", "Alaska", TRUE, FALSE, NA,
    "Pilot Station Traditional Village", "Alaska", TRUE, FALSE, NA,
    "Pitka's Point Traditional Council", "Alaska", TRUE, FALSE, NA,
    "Platinum Traditional Village", "Alaska", TRUE, FALSE, NA,
    "Portage Creek Village (aka Ohgsenakale)", "Alaska", TRUE, FALSE, NA,
    ## Printed line for the consolidated Pribilof entity — intentionally inactive:
    ## the entity is recovered via its two "(See ...)" redirects' short-form
    ## cross_reference_target; activating this long parenthetical form would
    ## split the entity into two distinct names downstream.
    #"Pribilof Islands Aleut Communities of St. Paul & St. George Islands (St. George Island and Saint Paul Island)", "Alaska", TRUE, FALSE, NA,
    "Qagan Tayagungin Tribe of Sand Point", "Alaska", TRUE, FALSE, NA,
    "Qawalangin Tribe of Unalaska", "Alaska", TRUE, FALSE, NA,
    "Rampart Village", "Alaska", TRUE, FALSE, NA,
    "St. George Island (See Pribilof Islands Aleut Communities of St. Paul & St. George Islands)", "Alaska", TRUE, TRUE, "Pribilof Islands Aleut Communities of St. Paul & St. George Islands",
    "Salamatof Tribe", "Alaska", TRUE, FALSE, NA,
    "Seldovia Village Tribe", "Alaska", TRUE, FALSE, NA,
    "Shageluk Native Village", "Alaska", TRUE, FALSE, NA,
    "Sitka Tribe of Alaska", "Alaska", TRUE, FALSE, NA,
    "Skagway Village", "Alaska", TRUE, FALSE, NA,
    "Stebbins Community Association", "Alaska", TRUE, FALSE, NA,
    "Sun'aq Tribe of Kodiak", "Alaska", TRUE, FALSE, NA,
    "Takotna Village", "Alaska", TRUE, FALSE, NA,
    "Tangirnaq Native Village", "Alaska", TRUE, FALSE, NA,
    "Telida Village", "Alaska", TRUE, FALSE, NA,
    "Traditional Village of Togiak", "Alaska", TRUE, FALSE, NA,
    "Tuluksak Native Community", "Alaska", TRUE, FALSE, NA,
    "Twin Hills Village", "Alaska", TRUE, FALSE, NA,
    "Ugashik Village", "Alaska", TRUE, FALSE, NA,
    "Umkumiut Native Village", "Alaska", TRUE, FALSE, NA,
    "Village of Alakanuk", "Alaska", TRUE, FALSE, NA,
    "Village of Anaktuvuk Pass", "Alaska", TRUE, FALSE, NA,
    "Village of Aniak", "Alaska", TRUE, FALSE, NA,
    "Village of Atmautluak", "Alaska", TRUE, FALSE, NA,
    "Village of Bill Moore's Slough", "Alaska", TRUE, FALSE, NA,
    "Village of Chefornak", "Alaska", TRUE, FALSE, NA,
    "Village of Clarks Point", "Alaska", TRUE, FALSE, NA,
    "Village of Crooked Creek", "Alaska", TRUE, FALSE, NA,
    "Village of Dot Lake", "Alaska", TRUE, FALSE, NA,
    "Village of Iliamna", "Alaska", TRUE, FALSE, NA,
    "Village of Kalskag", "Alaska", TRUE, FALSE, NA,
    "Village of Kaltag", "Alaska", TRUE, FALSE, NA,
    "Village of Kotlik", "Alaska", TRUE, FALSE, NA,
    "Village of Lower Kalskag", "Alaska", TRUE, FALSE, NA,
    "Village of Ohogamiut", "Alaska", TRUE, FALSE, NA,
    "Village of Red Devil", "Alaska", TRUE, FALSE, NA,
    "Village of Sleetmute", "Alaska", TRUE, FALSE, NA,
    "Village of Solomon", "Alaska", TRUE, FALSE, NA,
    "Village of Stony River", "Alaska", TRUE, FALSE, NA,
    "Village of Venetie (See Native Village of Venetie Tribal Government)", "Alaska", TRUE, TRUE, "Native Village of Venetie Tribal Government",
    "Village of Wainwright", "Alaska", TRUE, FALSE, NA,
    "Wrangell Cooperative Association", "Alaska", TRUE, FALSE, NA,
    "Yakutat Tlingit Tribe", "Alaska", TRUE, FALSE, NA,
    "Yupiit of Andreafski", "Alaska", TRUE, FALSE, NA
  )
}
